# Generated by Django 5.2.5 on 2025-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_library_librarybookitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Delivered At'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('sending', 'Sending')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='librarybookitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('reserved', 'Reserved'), ('lost', 'Lost')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='items',
            field=models.ManyToManyField(to='books.librarybookitem', verbose_name='Reserved Items'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
