# Generated by Django 5.2.5 on 2025-09-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reservation_delivered_at_reservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='delivered_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_date',
            field=models.DateTimeField(auto_now=True, verbose_name='status date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
