# Generated by Django 5.2.5 on 2025-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_reservation_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='library',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Date'),
        ),
    ]
