# Generated by Django 5.2.5 on 2026-04-15 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_city_country_remove_library_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='librarybookitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Library Book Item', 'verbose_name_plural': 'Library Book Items'},
        ),
        migrations.AddField(
            model_name='book',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved at'),
        ),
        migrations.AddField(
            model_name='book',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Librarian who approved this book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this book entry', on_delete=django.db.models.deletion.CASCADE, related_name='books_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='librarybookitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarybookitem',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='library_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_library', models.ForeignKey(blank=True, help_text='Library assigned to this user for managing book items', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.library', verbose_name='Assigned Library')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
