# Generated by Django 5.2.5 on 2026-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_options_alter_librarybookitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description/Summary'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Español', max_length=50, verbose_name='Language'),
        ),
    ]
