# Generated by Django 5.2.5 on 2026-04-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_cover_image_book_description_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_book', 'Can approve or reject books')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
