# Generated by Django 5.2.5 on 2026-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybookitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_library',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_libraries',
            field=models.ManyToManyField(blank=True, help_text='Libraries assigned to this user for managing book items', to='books.library', verbose_name='Assigned Libraries'),
        ),
    ]
