# Generated by Django 5.2.5 on 2026-04-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_librarybookitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='library',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='books.library', verbose_name='Library'),
            preserve_default=False,
        ),
    ]
