# Generated by Django 5.2.5 on 2026-04-29 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_reservation_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='librarybookitem',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Inventory Code'),
        ),
        migrations.AlterField(
            model_name='librarybookitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
