# Generated by Django 5.2.5 on 2026-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_language_alter_librarybookitem_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybookitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Library Book Item', 'verbose_name_plural': 'Library Book Items'},
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator',
            field=models.ManyToManyField(blank=True, related_name='illustrated_books', to='books.author', verbose_name='Illustrator'),
        ),
    ]
