# Generated by Django 5.2.5 on 2026-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_librarybookitem_options_book_illustrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='show_in_search',
            field=models.BooleanField(default=True, verbose_name='Show in search'),
        ),
        migrations.AddField(
            model_name='librarybookitem',
            name='show_in_search',
            field=models.BooleanField(default=True, verbose_name='Show in search'),
        ),
    ]
