"""
Django settings for libraries project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from environs import Env


env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY",default='django-insecure-ite81e+mgtqtc7z9#sk8=k^s43hnq#p7p1v9!oo^s$!2fk7hl4')
#SECRET_KEY = 'django-insecure-ite81e+mgtqtc7z9#sk8=k^s43hnq#p7p1v9!oo^s$!2fk7hl4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG",default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS",default=['localhost', ])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS",default=["http://localhost"])
CSRF_ALLOWED_ORIGINS = env.list("CSRF_ALLOWED_ORIGINS",default=["http://localhost"]) 
#CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE",default=False)
#SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE",default=False)
#SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT",default=False)
CORS_ORIGINS_WHITELIST = env.list("CORS_ORIGINS_WHITELIST",default=["http://localhost"]) 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libraries',
    'books',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'libraries.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'libraries.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env.str("DATABASE_NAME", default='siet_fe'),
        'USER': env.str("DATABASE_USER", default='root'),
        'PASSWORD': env.str("DATABASE_PASSWORD", default='password'),
        'HOST': env.str("DATABASE_HOST", default='localhost'),
        'PORT': env.str("DATABASE_PORT", default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

LANGUAGES = [
    ('es', 'Spanish'),
    ('en', 'English'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/Montevideo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = env.str("STATIC_URL", default='/static/')

# Para PythonAnywhere, el STATIC_ROOT debe ser en el directorio del proyecto
STATIC_ROOT = env.str("STATIC_ROOT", default=BASE_DIR / "static_collected")

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Altcha
ALTCHA_HMAC_KEY = env.str("ALTCHA_HMAC_KEY", default='altcha-development-key-change-in-production')

# Configuraciones adicionales para producción
if not DEBUG:
    # Configuraciones de seguridad para producción
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Para PythonAnywhere HTTPS
    # Descomenta estas líneas si usas HTTPS
    # SECURE_SSL_REDIRECT = True
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    
# Configuración de logging para producción
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'logs' / 'django.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }
